repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: name-tests-test
    args: [ --pytest-test-first ]
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.13.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
