version: 1
disable_existing_loggers: False
formatters:
  json:
    "()": pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s"
  json-access:
    "()": pythonjsonlogger.jsonlogger.JsonFormatter
    format: "%(asctime)s %(name)s %(levelname)s %(message)s %(levelprefix)s %(client_addr)s %(request_line)s %(status_code)s"
handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    stream: ext://sys.stdout
  console-access:
    class: logging.StreamHandler
    formatter: json
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]
loggers:
  uvicorn:
    level: INFO
    handlers: [console]
    propagate: False
  uvicorn.error:
    level: INFO
    handlers: [console]
    propagate: False
  uvicorn.access:
    level: INFO
    handlers: [console-access]
    propagate: False
  alembic.runtime.migration:
    level: INFO
    handlers: [console]
    propagate: False
