[project]
name = "fwordlesolver_api"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "django-ninja (>=1.3.0,<2.0.0)",
    "fwordlesolver (>=0.4.7,<0.5.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = true

[tool.poetry.group.dev.dependencies]
ruff = "^0.9.4"
pre-commit = "^4.1.0"
